# Hexo Configuration
## 官方文档: https://hexo.io/docs/configuration.html
## 源码仓库: https://github.com/hexojs/hexo/

# ========================
# 站点基本信息配置
# ========================
# Site
title: Fengxian Wang's Personal Homepage  # 网站标题（显示在浏览器标签页）
subtitle: ''                              # 网站副标题（可选）
description: ''                           # SEO描述（建议填写）
keywords:                                 # SEO关键词（多个用逗号分隔）
author: Fengxian Wang                     # 作者名称（显示在文章页）
language: en                              # 网站语言（zh-CN 中文简体）
timezone: ''                              # 时区（默认使用电脑时区，可设 Asia/Shanghai）

# ========================
# URL 地址配置
# ========================
# URL
## 如果部署到 GitHub Pages/Vercel 需设置为完整域名
url: https://academia-page-git-main-fengxian-wangs-projects.vercel.app/  # 网站根地址（必须包含协议头）
permalink: :title/                                                       # 文章永久链接格式
permalink_defaults:                                                      # 默认永久链接参数
pretty_urls:
  trailing_index: true                                                   # 是否在目录后保留 index.html（false 则 /about/ 变为 /about）
  trailing_html: true                                                    # 是否保留 .html 扩展名（false 则 /about.html 变为 /about）

# ========================
# 目录结构配置
# ========================
# Directory
source_dir: source        # 源文件目录（Markdown/模板等）
public_dir: public        # 生成静态文件的目录（勿改）
tag_dir: tags             # 标签页面目录
archive_dir: archives     # 归档目录
category_dir: categories  # 分类目录
code_dir: downloads/code  # 代码文件存放路径
i18n_dir: :lang           # 国际化文件目录
skip_render:
  - admin/**     # 跳过 Netlify CMS 管理界面的渲染
  - 404.html     # 保留自定义404页面

# ========================
# 文章编写配置
# ========================
# Writing
new_post_name: :title.md   # 新文章文件名格式（可用日期 :year-:month-:day-:title.md）
default_layout: post       # 默认模板布局（post/page/draft）
titlecase: false           # 是否自动转换标题为首字母大写（中文慎用）
external_link:
  enable: true    # 是否在新标签页打开外部链接
  field: site      # 应用范围（site-全站 / post-仅文章）
  exclude: ''      # 排除的域名（逗号分隔）
filename_case: 0   # 文件名转换（0-禁用 1-小写）
render_drafts: false  # 是否渲染草稿
post_asset_folder: false  # 是否启用资源文件夹（true则每篇文章有独立文件夹）
relative_link: false  # 是否生成相对链接（用于本地文件系统）
future: true        # 是否渲染未来日期的文章

# 代码高亮配置
highlight:
  enable: true      # 启用代码高亮
  line_number: true # 显示行号
  auto_detect: false # 自动语言检测（可能影响性能）
  tab_replace: ''    # 替换制表符（例如用2空格）
  wrap: true         # 添加外层容器
  hljs: false       # 是否使用 hljs 兼容模式

# 另一种代码高亮方案（与highlight二选一）
prismjs:
  enable: false     # 启用 Prism.js
  preprocess: true  # 预处理代码块
  line_number: true 
  tab_replace: ''

# ========================
# 首页配置
# ========================
# Home page setting
index_generator:
  path: ''          # 首页路径（默认根目录）
  per_page: 10      # 每页显示文章数（0禁用分页）
  order_by: -date   # 排序方式（-date表示按发布时间倒序）

# ========================
# 分类和标签配置
# ========================
# Category & Tag
default_category: uncategorized  # 默认分类（当未指定分类时使用）
category_map:                    # 分类别名映射（例如: tech: Technology）
tag_map:                         # 标签别名映射

# ========================
# 元数据配置
# ========================
# Metadata elements
meta_generator: true  # 是否生成<meta generator="Hexo">标签（SEO相关）

# ========================
# 日期格式配置
# ========================
# Date / Time format
## 使用 Moment.js 格式：http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD          # 日期显示格式
time_format: HH:mm:ss           # 时间显示格式
updated_option: 'mtime'         # 更新日期依据（mtime-文件修改时间 / date-Front Matter日期）

# ========================
# 分页配置
# ========================
# Pagination
per_page: 10         # 全局分页数量（会被各页面的配置覆盖）
pagination_dir: page # 分页目录名称（如第2页路径为 /page/2/）

# ========================
# 文件包含/排除配置
# ========================
# Include / Exclude file(s)
include:     # 强制包含文件/目录（支持 glob 表达式）
exclude:     # 排除文件/目录（支持 glob 表达式）
ignore:      # 忽略文件（生成时跳过）

# ========================
# 主题和插件配置
# ========================
# Extensions
theme: Academia  # 当前使用主题（主题需放在themes目录下）
## 插件列表（需先npm安装）
plugins:
  - hexo-generator-feed  # RSS生成示例（需安装）

# ========================
# 部署配置
# ========================
# Deployment
## 示例配置（需先安装 hexo-deployer-git）：
# deploy:
#   type: git
#   repo: <repository url>  # 代码仓库地址
#   branch: main            # 部署分支
#   token: $GH_TOKEN        # GitHub Token（用于私有仓库）
