# ========================
# 基本个人信息配置
# ========================
# 网站图标路径（建议尺寸：32x32 或 64x64 像素）
favicon: /img/favicon.png

# 头像路径（建议尺寸：200x200 像素正方形）
avatar: /img/profile.jpg

# 作者名称（如果hexo主配置已设置author，此处不生效）
author: 'fengxian Wang'

# 作者简介（显示在个人主页）
author_bio: 'Doctoral student in HEBUT'

# 建站年份（显示在页脚版权信息）
since: 2025


# ========================
# 导航菜单配置
# ========================
# 格式：显示名称: 链接路径（支持锚点#）
# 示例：Publications: /publications#journal
menu:
  Publications: /publications


# ========================
# 加载状态配置
# ========================
# 头像加载失败时的备用背景图
loading_bg:
  flink: /img/profile.png


# ========================
# 社交链接配置
# ========================
# 启用标准社交图标（true/false）
social:
  enable: true

# 社交平台配置（使用Font Awesome 4.7图标）
# 格式：fab fa-平台名称: 链接地址
social_links:
#  fab fa-twitter: /                                     # 推特
#  fab fa-facebook-square: /                             # 脸谱
  fab fa-github: https://github.com/Fengxian-wang        # Github
#  fab fa-stack-overflow: /                              #‌ Stack Overflow
  fab fa-dashboard: /admin/                                     # 领英
#  fab fa-weibo: /                                       # 微博
  fab fa-weixin: /img/wechat.jpg                         # 微信
#  fab fa-qq: /                                          # 企鹅
  fas fa-envelope: mailto:fx-wang@outlook.com            # 邮箱
#  fas fa-rss: /                                         # RSS订阅
  fab fa-linkedin: /admin/                              # 后台


# ========================
# 扩展社交链接配置
# ========================
# 启用自定义社交链接（true/false）
e_social:
  enable: true

# 自定义链接格式：显示名称: 链接地址 || 图标类名
# 示例：Google Scholar: https://scholar.com || fas fa-graduation-cap
e_social_links:
  Google Scholar: https://scholar.google.com.hk/citations?hl=zh-CN&user=WkrkOpgAAAAJ || fas fa-graduation-cap        # Google Scholar
  ORCID: https://orcid.org/0009-0004-9435-6979 || fab fa-orcid                                                       # ORCID


# ========================
# 简历下载配置
# ========================
cv_dl:
  enable: true        # 启用下载按钮
  dir: /attaches/CV.pdf  # PDF文件路径（建议放在source/attaches目录）
  description: My Detail CV.  # 鼠标悬停提示文字


# ========================
# 视觉效果配置
# ========================
# 是否启用卡片阴影效果（true/false）
box_shadow:
  enable: false


# ========================
# 资源加载配置
# ========================
# 自定义CSS/JS文件加载（路径从source目录开始）
CDN_USE:
  css:
    - /css/index.css                       # 本地CSS文件
    - https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.13.0/css/all.min.css  # FontAwesome 5
  js:
    - https://cdn.jsdelivr.net/npm/jquery@latest/dist/jquery.min.js          # jQuery库
    - https://cdn.jsdelivr.net/npm/jquery-pjax@latest/jquery.pjax.min.js    # PJAX插件
    - /js/main.js                                                           # 本地JS文件


# ========================
# 数学公式支持
# ========================
mathjax:
  enable: true  # 启用MathJax渲染
  cdn: https://cdn.jsdelivr.net/npm/mathjax@2.7.8/MathJax.js?config=TeX-MML-AM_CHTML  # CDN地址


# ========================
# 访问统计配置
# ========================
statistic:
  enable: true  # 启用不蒜子统计
  cdn: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-busuanzi@2.3/js/busuanzi.pure.mini.js  # 统计脚本
